### Submit Suppliers
GET http://localhost:4004/catalog/Suppliers?$top=2

### Browse Products
GET http://localhost:4004/catalog/Products?$top=2

### Browse Products - Product,Identifier ,Price
GET http://localhost:4004/catalog/Products?
&$select=identifier,price

### Submit Products
POST http://localhost:4004/catalog/Products
Content-Type: application/json

{ 
    "identifier": "MK-CH-1002",
    "title" : "Mike Test"

}